# Generated by Django 4.1.2 on 2022-11-02 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='assistance_category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('section', models.IntegerField()),
                ('date', models.DateField()),
                ('class_total', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='faculty',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='professor',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('carnet', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='semester',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('faculty_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cors.faculty')),
            ],
        ),
        migrations.CreateModel(
            name='qr',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('limit_date', models.DateField()),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cors.course')),
            ],
        ),
        migrations.CreateModel(
            name='device',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('qr_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cors.qr')),
            ],
        ),
        migrations.CreateModel(
            name='course_student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cors.course')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cors.student')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='faculty_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cors.faculty'),
        ),
        migrations.AddField(
            model_name='course',
            name='professor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cors.professor'),
        ),
        migrations.AddField(
            model_name='course',
            name='semester_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cors.semester'),
        ),
        migrations.CreateModel(
            name='assistance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('observations', models.CharField(max_length=200)),
                ('assistance_category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cors.assistance_category')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cors.course')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cors.student')),
            ],
        ),
    ]