# Generated by Django 3.0.8 on 2022-10-20 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaAsistencia',
            fields=[
                ('idFacultad', models.IntegerField(primary_key=True, serialize=False)),
                ('Tipo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ciclo',
            fields=[
                ('idCiclo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('idCurso', models.IntegerField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=50)),
                ('Seccion', models.IntegerField()),
                ('Anio', models.DateField()),
                ('Ciclo_idciclo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cors.Ciclo')),
            ],
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('carnet', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=50)),
                ('firebaseid', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Facultad',
            fields=[
                ('idFacultad', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('Carnet', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=50)),
                ('Correo', models.CharField(max_length=50)),
                ('Facultad_idFacultad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cors.Facultad')),
            ],
        ),
        migrations.CreateModel(
            name='Curso_has_Estudiante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Curso_idCurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cors.Curso')),
                ('Estudiante_carnet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cors.Estudiante')),
            ],
        ),
        migrations.AddField(
            model_name='curso',
            name='Docente_Carnet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cors.Docente'),
        ),
        migrations.AddField(
            model_name='curso',
            name='Facultad_idFacultad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cors.Facultad'),
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('idAsistencia', models.IntegerField(primary_key=True, serialize=False)),
                ('Fecha', models.DateField()),
                ('Observacion', models.CharField(max_length=200)),
                ('CategoriasAsistencia_idCategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cors.CategoriaAsistencia')),
                ('Curso_idCurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cors.Curso')),
                ('Estudiante_Carnet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cors.Estudiante')),
            ],
        ),
    ]
