# Generated by Django 4.1.2 on 2022-10-21 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaAsistencia',
            fields=[
                ('idFacultad', models.AutoField(primary_key=True, serialize=False)),
                ('Tipo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ciclo',
            fields=[
                ('idCiclo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('idCurso', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=50)),
                ('Seccion', models.IntegerField()),
                ('Anio', models.DateField()),
                ('TotalClases', models.IntegerField()),
                ('Ciclo_idciclo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cors.ciclo')),
            ],
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('carnet', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=50)),
                ('firebaseid', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Facultad',
            fields=[
                ('idFacultad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Qr',
            fields=[
                ('idQr', models.AutoField(primary_key=True, serialize=False)),
                ('FechaLimite', models.DateField()),
                ('Imagen', models.ImageField(upload_to='')),
                ('Curso_idCurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cors.curso')),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('Carnet', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=50)),
                ('Correo', models.CharField(max_length=50)),
                ('Facultad_idFacultad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cors.facultad')),
            ],
        ),
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('idDispositivo', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=45)),
                ('Qr_idQr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cors.qr')),
            ],
        ),
        migrations.CreateModel(
            name='Curso_has_Estudiante',
            fields=[
                ('Curso_idCurso', models.AutoField(primary_key=True, serialize=False)),
                ('Estudiante_carnet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cors.estudiante')),
            ],
        ),
        migrations.AddField(
            model_name='curso',
            name='Docente_Carnet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cors.docente'),
        ),
        migrations.AddField(
            model_name='curso',
            name='Facultad_idFacultad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cors.facultad'),
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('idAsistencia', models.AutoField(primary_key=True, serialize=False)),
                ('Fecha', models.DateField()),
                ('Observacion', models.CharField(max_length=200)),
                ('CategoriasAsistencia_idCategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cors.categoriaasistencia')),
                ('Curso_idCurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cors.curso')),
                ('Estudiante_Carnet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cors.estudiante')),
            ],
        ),
    ]
