# Generated by Django 4.1.2 on 2022-11-02 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='student_id',
        ),
        migrations.AddField(
            model_name='course',
            name='student_id',
            field=models.ManyToManyField(related_name='student', to='cors.student'),
        ),
    ]
