# Generated by Django 4.1.2 on 2022-10-21 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qr',
            name='Imagen',
        ),
    ]
