# Generated by Django 4.1.2 on 2022-11-02 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cors', '0002_alter_course_class_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='date',
        ),
    ]
