# Generated by Django 4.1.2 on 2022-11-03 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cors', '0003_remove_course_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='qr',
            name='latitude',
            field=models.FloatField(default=14.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='qr',
            name='longitude',
            field=models.FloatField(default=20.0),
            preserve_default=False,
        ),
    ]
