# Generated by Django 4.1.2 on 2022-11-03 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cors', '0004_qr_latitude_qr_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qr',
            name='limit_date',
            field=models.DateTimeField(),
        ),
    ]
