# Generated by Django 4.1.2 on 2022-11-03 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cors', '0007_student_device_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
