# Generated by Django 4.1.2 on 2022-11-03 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cors', '0008_alter_device_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='device_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='cors.device', unique=True),
        ),
    ]
