# Generated by Django 4.1.2 on 2022-11-04 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cors', '0009_alter_student_device_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assistance',
            old_name='assistance_category_id',
            new_name='assistance_category',
        ),
        migrations.RenameField(
            model_name='assistance',
            old_name='course_id',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='assistance',
            old_name='student_id',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='faculty_id',
            new_name='faculty',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='professor_id',
            new_name='professor',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='semester_id',
            new_name='semester',
        ),
        migrations.RenameField(
            model_name='course_student',
            old_name='course_id',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='course_student',
            old_name='student_id',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='device',
            old_name='qr_id',
            new_name='qr',
        ),
        migrations.RenameField(
            model_name='qr',
            old_name='course_id',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='device_id',
            new_name='device',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='faculty_id',
            new_name='faculty',
        ),
    ]
