# Generated by Django 4.1.2 on 2022-11-04 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cors', '0010_rename_assistance_category_id_assistance_assistance_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='device',
        ),
        migrations.AddField(
            model_name='course',
            name='student_id',
            field=models.ManyToManyField(related_name='student', to='cors.student'),
        ),
        migrations.AddField(
            model_name='device',
            name='student',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='cors.student', unique=True),
        ),
        migrations.AlterField(
            model_name='qr',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr', to='cors.course'),
        ),
    ]
