# Generated by Django 4.1.2 on 2022-11-04 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cors', '0011_remove_student_device_course_student_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course', to='cors.professor'),
        ),
        migrations.AlterField(
            model_name='course',
            name='student_id',
            field=models.ManyToManyField(related_name='courses', to='cors.student'),
        ),
    ]
