# Generated by Django 4.1.2 on 2022-11-04 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cors', '0012_alter_course_professor_alter_course_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='faculty',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='course',
            name='semester',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='student',
            name='faculty',
            field=models.CharField(max_length=25),
        ),
    ]
